git add run/funcs.sh
git add src/LoadData/LoadDataWorker.java
git add src/client/jTPCC.java
git add src/client/jTPCCConfig.java
git add src/client/jTPCCConnection.java
git add add.sh
git add lib/mysql/
git add lib/yugabyte/
git add run/props.mysql
git add run/props.tidb
git add run/props.yuga
git add run/sql.mysql/
git add run/sql.tidb/
git add run/sql.yugabyte/
